### ISSUE TITLE
About labs

### ISSUE THREAD

**Issue by CaptWorld** [PKUFlyingPig/EE16A#1]
Hey, are u a student of ucb? If not, how did you do the labs?

**Comment by PKUFlyingPig** [comment]
Codes and handouts are free to everyone, you can buy the electronic components as needed.

**Comment by CaptWorld** [comment]
oh.. so you bought those components to do the labs?

**Comment by PKUFlyingPig** [comment]
Exactly, except for some labs which require specific components which can not be bought on the Internet.

**Comment by CaptWorld** [comment]
Oh ok. Thanks for the info.
